<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0-windows;net48</TargetFrameworks>
		<Nullable>enable</Nullable>
		<LangVersion>12</LangVersion>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>

		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageId>Junevy.Controls</PackageId>
		<Version>1.2.2</Version>
		<Authors>Junevy</Authors>
		<Company>Junevy</Company>
		<Description>Junevy WPF Controls</Description>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net48'">
		<Reference Include="System.Xaml" />
		<Reference Include="WindowsBase" />
		<Reference Include="PresentationCore" />
		<Reference Include="PresentationFramework" />
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="Controls\Menu\MenuItem.NodeType.cs" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Resources\Font\iconfont.ttf" />
	  <None Remove="Resources\Pictures\Author.png" />
	  <None Remove="Resources\Pictures\bullseye.png" />
	  <None Remove="Resources\Pictures\camera.png" />
	  <None Remove="Resources\Pictures\whiteCheckBoard_big.png" />
	</ItemGroup>

	<ItemGroup>
		<None Include="Controls\Menu\MenuItem.NodeType.cs" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Resources\Font\iconfont.ttf" />
	  <Resource Include="Resources\Pictures\Author.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\Pictures\bullseye.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\Pictures\camera.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\Pictures\whiteCheckBoard_big.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>


	<ItemGroup>
		<Page Update="Themes\Generic.xaml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Page>
	</ItemGroup>

</Project>
