<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>Junevy.Controls.Showcase</RootNamespace>
		<AssemblyName>Junevy.Controls.Showcase</AssemblyName>
		<Description>Junevy.Controls 控件库分类展示程序</Description>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Junevy.Controls.csproj" />
	</ItemGroup>

</Project>
